### ISSUE TITLE
Displaying feature attributes when a marker is clicked

### ISSUE THREAD

**Issue by govvin** [plepe/OpenStreetBrowser#193]
Right now whenever I see a marker on the map and click on it, it shows just the following:

![image](https://github.com/plepe/OpenStreetBrowser/assets/5821688/61f83619-8ab6-4e58-9794-deb7f2b94cc5)

I don't remember which OSB category (or custom category) feature I saw, where instead of the above, the window actually display the attributes for the feature.

What do I need to add to a custom category to make that happen?

**Comment by plepe** [comment]
I think of the popups as a "user-friendly" display of the information about the map feature. Would you like any specific tags which should be shown in the popup?

You can see all attributes of the feature when you click 'show details'.

**Comment by govvin** [comment]
Yes, I understand that you can see more more information when you click on "show details" but what I meant to ask is that how to display the tags/attributes  by default, without clicking anything. 

I know I've seen it work with a custom category, but couldn't remember which one, and hope to learn how to replicate that behavior.

**Comment by plepe** [comment]
Ah, I see.

The easiest would be the following snippet, which formats the tags as YAML output:
```yaml
query: nwr[whatever=you_want]
feature:
  body: "<pre>{{ tags|yaml }}</pre>"
```

Alternatively, you could also use:
```yaml
query: nwr[whatever=you_want]
feature:
  body: |
    {% for k, v in tags %}
    {{ k }}: {{ v }}<br>
    {% endfor %}
```

I hope this is helpful for you.

Learn more about how to create custom categories:
* [Tutorial](https://github.com/plepe/OpenStreetBrowser/blob/master/doc/Tutorial.md)
* [Documentation about TwigJS](https://github.com/plepe/OpenStreetBrowser/blob/master/doc/TwigJS.md)
